apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
  labels:
    app: welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome123
        image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000      