apiVersion: apps/v1
kind: deployment
metadata:
  name: welcome-deployment
  labels:
    app: welcome
spec:
    replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        appli: welcome # label doesn't match replica selector
    spec:
      container:
      - name: welcome123
        image: tristan12/welcome-to-docker:tpexo12
        ports:
        - containerPort: 3000      